services:
  db:
    image: mysql:8.0
    container_name: gastrocontrol-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gastrocontrol
      MYSQL_USER: gastrocontrol
      MYSQL_PASSWORD: gastrocontrol
    ports:
      - "3307:3306"
    volumes:
      - gastro_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - gastrocontrol-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"]
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gastrocontrol-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: "dev-super-long-random-string-change-me"
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: gastrocontrol
      DB_USER: gastrocontrol
      DB_PASSWORD: gastrocontrol
    networks:
      - gastrocontrol-net

networks:
  gastrocontrol-net:
    driver: bridge

volumes:
  gastro_mysql_data:
