services:
  db:
    image: mysql:8.0
    container_name: gastrocontrol-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gastrocontrol
      MYSQL_USER: gastrocontrol
      MYSQL_PASSWORD: gastrocontrol
    ports:
      - "3307:3306"
    volumes:
      - gastro_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - gastrocontrol-net
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent"]
      interval: 3s
      timeout: 3s
      retries: 30
      start_period: 10s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gastrocontrol-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: "dev-super-long-random-string-change-me"
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: gastrocontrol
      DB_USER: gastrocontrol
      DB_PASSWORD: gastrocontrol
      MAILGUN_API_KEY: ${MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_BASE_URL: ${MAILGUN_BASE_URL:-https://api.eu.mailgun.net}
      MAIL_FROM_EMAIL: ${MAIL_FROM_EMAIL:-no-reply@jonathan-hendrix.dev}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME:-GastroControl}
      STRIPE_API_KEY: ${STRIPE_API_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_CURRENCY: ${STRIPE_CURRENCY:-eur}
      STRIPE_CHECKOUT_SUCCESS_URL: ${STRIPE_CHECKOUT_SUCCESS_URL:-http://localhost:4200/checkout/success?session_id={CHECKOUT_SESSION_ID}}
      STRIPE_CHECKOUT_CANCEL_URL: ${STRIPE_CHECKOUT_CANCEL_URL:-http://localhost:4200/checkout/cancel?session_id={CHECKOUT_SESSION_ID}}
    networks:
      - gastrocontrol-net

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: gastrocontrol-stripe-cli
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - gastrocontrol-net
    environment:
      STRIPE_API_KEY: ${STRIPE_API_KEY}
    volumes:
      - stripe_cli_config:/root/.config/stripe
    command: >
      listen
      --api-key ${STRIPE_API_KEY}
      --forward-to http://api:8080/api/webhooks/stripe
      --events checkout.session.completed
      --log-level info

networks:
  gastrocontrol-net:
    driver: bridge

volumes:
  gastro_mysql_data:
  stripe_cli_config:
