spring:
  application:
    name: gastrocontrol

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:gastrocontrol}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER:gastrocontrol}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate       # dev only; later we'll move to migrations
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    open-in-view: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  flyway:
    enabled: true
    locations:
      - classpath:db/migration
      - classpath:db/dev-migration
    baseline-on-migrate: true
    clean-disabled: true   # safety: prevents accidental 'flyway clean'


security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: 900 # access token, e.g. 15 minutes
  refresh:
    expiration-days: 14
    cookie:
      name: refresh_token
      same-site: Lax      # dev-friendly; prod often None
      secure: false       # prod true


server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
