spring:
  application:
    name: gastrocontrol

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:gastrocontrol}?useSSL=false&serverTimezone=UTC
    username: ${DB_USER:gastrocontrol}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true

mail:
  enabled: ${MAIL_ENABLED:false}
  from:
    email: ${MAIL_FROM_EMAIL:no-reply@jonathan-hendrix.dev}
    name: ${MAIL_FROM_NAME:GastroControl}
  mailgun:
    api-key: ${MAILGUN_API_KEY:}
    domain: ${MAILGUN_DOMAIN:}
    base-url: ${MAILGUN_BASE_URL:https://api.eu.mailgun.net}

security:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: 900
  refresh:
    expiration-days: 14
    cookie:
      name: refresh_token
      same-site: Lax
      secure: false

stripe:
  api-key: ${STRIPE_API_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
  currency: ${STRIPE_CURRENCY:eur}

  # These are the URLs Stripe will redirect to after Checkout.
  # Youâ€™ll typically set them to frontend routes.
  checkout-success-url: ${STRIPE_CHECKOUT_SUCCESS_URL:http://localhost:4200/checkout/success?session_id={CHECKOUT_SESSION_ID}}
  checkout-cancel-url: ${STRIPE_CHECKOUT_CANCEL_URL:http://localhost:4200/checkout/cancel?session_id={CHECKOUT_SESSION_ID}}


server:
  port: 8080

app:
  public:
    base-url: ${APP_PUBLIC_BASE_URL:http://localhost:8080}
  frontend:
    base-url: ${APP_FRONTEND_BASE_URL:http://localhost:4200}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
